# Site settings
title: Erik Nilsen
email: erik@erikdnilsen.com
description: "Full Stack Web Developer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/eriknilsen16
  - title: github
    url: http://github.com/enilsen16
  - title: linkedin
    url: http://linkedin.com/in/erikdnilsen

# Postal address (add as many lines as necessary)
address:
  - line: Greater Seattle Area

# Build settings
markdown: kramdown
permalink: pretty

exclude:
 - unicorn.rb
 - README.md
 - Procfile
 - Gemfile
 - Gemfile.lock
 - config.ru
 - vendor
 - app.json
