title: Erik Nilsen
email: enilsen16@live.com
url: http://www.erikdnilsen.com
description: "Personal website for Erik Nilsen, Ruby and JavaScript Developer."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/enilsen16
  - title: github
    url: http://github.com/enilsen16
  - title: linkedin
    url: http://linkedin.com/in/erikdnilsen

# Postal address (add as many lines as necessary)
address:
  - line: Seattle, WA

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
